/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  bnsSidebar: [
    "intro",
    {
      type: "category",
      collapsed: false,
      label: "Understand BNS",
      items: ["names-namespaces", "subdomains", "zonefiles"],
    },
    "history-of-bns",
    "ecosystem",
    {
      label: "L1 Bridge",
      type: "category",
      collapsed: false,
      items: [
        "l1-bridge/overview",
        "l1-bridge/how-to-bridge-l1",
        "l1-bridge/l1-api",
      ],
    },
    {
      type: "category",
      collapsed: true,
      items: [
        "bnsx/intro",
        {
          type: "category",
          label: "Protocol",
          collapsed: false,
          items: [
            "bnsx/contracts",
            "bnsx/protocol-registry",
            "bnsx/protocol-wrapping",
            "bnsx/protocol-migrator",
          ],
        },
        "bnsx/integration-faq",
        {
          type: "link",
          label: "Contract Documentation",
          href: "https://github.com/mechanismHQ/bns-x/tree/main/docs",
        },
      ],
      label: "BNSx",
    },
    {
      type: "category",
      collapsed: false,
      label: "Developer Tools",
      items: [
        "developer-tools/api",
        "developer-tools/bns-client",
        "developer-tools/hiro-tools",
        "bns-contract",
      ],
    },
    {
      type: "category",
      link: {
        id: "dots/index",
        type: "doc",
      },
      label: "Dots",
      items: [
        "dots/migrate-multiple-accounts",
        "dots/renew",
        "dots/unwrap-bnsx",
        "dots/update-zonefile",
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
